Task_1_1_2
vil-mo/OOP pull request #2
Opened 2024-09-17 02:29 UTC by vil-mo

2024-09-18 02:27 UTC, vil-mo commented
У меня вопрос
reviewdog несколько раз жалуется на `switch without "default" clause` в фале `Game`, хотя паттерн там exhaustive. Я думаю, если патерн exhaustive добавлять там default бесполезно / может быть даже вредно? 
Почему-то reviewdog не жалуется на это в классе `Card`.

2024-09-24 08:59 UTC, shadrina requested changes

2024-09-24 08:59 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/berezin/Dealer.java
> +    ArrayList<Card> dealerHand = new ArrayList();
Модификаторы доступа?

2024-09-24 08:59 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/berezin/GameInterface.java
> +package ru.nsu.berezin;
В начале пары рассказывала

2024-09-24 08:59 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/berezin/GameInterface.java
> +public interface GameInterface<E extends Exception> {
Давай уберем зависимость от исключения

2024-10-01 08:43 UTC, shadrina approved these changes

2024-10-01 08:43 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/berezin/blackjack/Dealer.java
> +    public Card openDealerCard() throws IndexOutOfBoundsException {
Лучше кидать проверяемое

2024-10-01 08:49 UTC, merged